name: DAST Scan

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t devsecops-app .

      - name: Run app container
        run: docker run -d -p 5000:5000 --name web devsecops-app

      - name: Wait for service
        run: sleep 20

      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run --rm --network host \
            -v ${{ github.workspace }}:/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py -t http://127.0.0.1:5000 -a -r zap_report.html || true

      - name: Verify ZAP Report
        run: ls -l zap_report.html || echo "⚠️ zap_report.html not found"

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap_report.html
