name: DAST Scan

on:
  workflow_dispatch:  # chạy thủ công
  push:
    branches: [ "main" ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t devsecops-app .

      - name: Run app in background
        run: docker run -d -p 5000:5000 devsecops-app

      - name: Wait for service
        run: sleep 15

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: "http://localhost:5000"
          rules_file_name: ".zap/rules.tsv"
          cmd_options: "-a"
